# To be used by kustomize
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: greeting-a
  annotations:
    sonataflow.org/description: Greeting example on k8s!
    sonataflow.org/version: 0.0.5
spec:
  flow:
   start: say-hello 
   functions:
     - name: sayhello
       operation: specs/simple-service.yaml#hello
   states:
     - name: say-hello
       type: operation
       actions:
         - name: sayhello 
       end: true
  resources:
    configMaps:
      - configMap:
          name: openapi-specs-a
        workflowPath: specs

