# To be used by kustomize
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: greeting-b
  annotations:
    sonataflow.org/description: Greeting example on k8s!
    sonataflow.org/version: 0.0.2
    sonataflow.org/profile: dev
spec:
  flow:
   start: foo
   state:
     name: foo
     end: true
resources:
    configMaps:
      - configMap: configmap
        workflowPath: specs
