apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonataflow.yaml
  - configMap.yaml
configurations:
  - nameReference.yaml
configMapGenerator:
  - name: openapi-specs-b
    files:
      - specs/simple-service.yaml
