# To be used by kustomize
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: mta
  annotations:
    sonataflow.org/description: MTA analysis workflow
    sonataflow.org/version: 0.0.5
spec:
  flow:
   start: say-hello
   dataInputSchema:
     schema: specs/mta-schema.json
     failOnValidationErrors: true
   functions:
     - name: sayhello
       operation: specs/simple-service.yaml#hello
   states:
     - name: say-hello
       type: operation
       actions:
         - functionRef: sayhello
       transition: inject
     - name: inject
       type: inject
       data:
         analysis: MTA analysis done
       end: true
  resources:
    configMaps:
      - configMap:
          name: openapi-specs-a
        workflowPath: specs

